#!/bin/sh

#################################################################
##         REMOVE PREVIOUS FIREFOX FROM /APPLICATIONS	       ##
################################################################# 

if [ -d "$3/Applications/Firefox.app" ]; then
   rm -rf "$3/Applications/Firefox.app"
fi

