#!/bin/bash

# preinstall.sh
# Marc Thielemann, 2016/04/04

# redirect all output to /dev/null
exec >/dev/null 2>&1

/usr/bin/killall Privileges

# unload the launchd plist only if installing on the boot volume
if [[ "$3" = "/" ]]; then
	/bin/launchctl unload "$3/Library/LaunchDaemons/corp.sap.privileges.helper.plist"
fi

/bin/rm -rf "$3/Library/LaunchDaemons/corp.sap.privileges.helper.plist" \
            "$3/Library/PrivilegedHelperTools/corp.sap.privileges.helper" \
            "$3/Applications/Privileges.app"

exit 0